version: '3.0'

services:

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./api_server/.dev.env
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d
      - local_pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin_data: